# Site settings
author: Alexandria Branner
title: “Why did I decide to study Software Engineering?”
header-img: img/home-bg.png
email: ahartpro87@gmail.com
copyright_name: Alexandria Branner
description: > # this means to ignore newlines until "baseurl:"
  New To Software Engineering
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  AlexandriaBranner87

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
